#device.processor.url=http://150.163.5.83:8080/


# URL padrão usada no container ou em produção (com a porta 8080 inclusa)
device.processor.url=http://host.docker.internal:8080

# URL usada apenas quando você estiver rodando localmente em modo de desenvolvimento
%dev.device.processor.url=http://localhost:8080/


quarkus.http.port=8088